services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ErHaWeb\DinosaurFinder\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  ErHaWeb\DinosaurFinder\Service\DinosaurService:
    public: true
